### ISSUE TITLE
astroquery problem in Exercise_1.ipynb

### ISSUE THREAD

**Issue by aaastorrs** [NASA-NAVO/navo-workshop#23]
I am trying to run the Exercise_1 Jupyter notebook and apparently NED isn't part of my installation of astroquery-- I get:

ImportError: cannot import name 'Ned' from 'astroquery.ned' (unknown location)

Is there a workaround for this?

Thanks!

**Comment by xiuqin** [comment]
It works with my version of astroquery 0.4.1. Could you please check which version you have installed?
You may use this command to upgrade it:  pip install --pre --upgrade astroquery --use-deprecated=legacy-resolver

**Comment by aaastorrs** [comment]
Thanks! I'm afraid this wasn't the problem, and in addition the ssa query I copied from the documentation has stopped working, complaining that:

DALServiceError: 502 Server Error: Proxy Error for url: http://www.isdc.unige.ch/vo-services/lc?POS=83.63308333%2C22.0145&SIZE=0.5&BAND=1e-07%2F1e-06&TIME=2015-01-01T00%3A00%3A00.000%2F2018-01-01T00%3A00%3A00.000&FORMAT=all&REQUEST=queryData

The query from the AAS workshop still gives "skipping" for all sources.

Does this go to github as well, or should I copy it there?

Thanks again!

Alex Storrs

**Comment by aaastorrs** [comment]
So today my ssa query worked. Must have been a server problem at their end.


Still having trouble with the webinar example. My (windows) version of pip doesn't understand "--use-deprecated=legacy-resolver" so I updated without it. Lots of "requirement already satisfied" and a bunch of warnings, each ending in "inconsistent version: filename has '0.4.2.dev6193', but metadata has '0.4.2.dev0'"

Same result as my original problem-all the services are "not working: skipping"



Is there some fundamental setup step done by the illuminati of which I do not ken?



Thanks!



Alex

**Comment by stargaser** [comment]
@aaastorrs For the `Ned.query_refcode` calls, I am encountering some difficulties in some environments. It might be better for now to do `pip uninstall astroquery` and then do `conda install astroquery` which will give you v0.4.1.

I am also encountering an error with sia queries to ivo://archive.stsci.edu/sia/galex but that sounds different than the errors you are running into?

Would you please run `python check_env.py` (file in top level of the repository) and post the output?

**Comment by aaastorrs** [comment]
Found jupyter
Found notebook 6.3.0
Found numpy 1.20.2
Found scipy 1.6.2
Found skimage 0.18.1
Found matplotlib 3.4.0
Found bs4 4.9.3
Error: Failed import: No module named 'keyring'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\Documents\Python_Scripts\check_env.py in <module>
     65
     66 if __name__ == '__main__':
---> 67     run_checks()

~\Documents\Python_Scripts\check_env.py in run_checks()
     56     errors = []
     57     for package_name, min_version in PKGS.items():
---> 58         errors.append(check_package(package_name, minimum_version=min_version))
     59     if any(errors):
     60         print('\nThere are errors that you must resolve before running the '

~\Documents\Python_Scripts\check_env.py in check_package(package_name, minimum_version, verbose)
     41             installed_version = pkg.__VERSION__
     42         else:
---> 43             installed_version = pkg.__version__
     44         if (minimum_version is not None and
     45                 LooseVersion(installed_version) <

AttributeError: module 'html5lib' has no attribute '__version__'

**Comment by stargaser** [comment]
@aaastorrs for the NED issues you encountered, a server-side fix has been implemented. It should work with your version of astroquery.

Over this past weekend, astroquery v0.4.2 was released to PyPI.org so you can now simply `pip install astroquery`.

For your other queries that are being skipped: would you please provide more details? We would like to help if these are still not working.
